import { getSiteContent } from "@/lib/site-content";
import { absoluteUrl } from "@/lib/seo";

export async function GET() {
  const content = await getSiteContent();
  const baseUrl = absoluteUrl("/", content);
  const text = [
    "# Digital Dot",
    "",
    "Digital Dot este o agenție de marketing digital din România, parte din IONNEL TECH SRL, specializată în strategie de marketing, Social Media Management, producție foto-video, Google Ads, Meta Ads, Website Creation, SEO și AI SEO.",
    "",
    "Website:",
    baseUrl,
    "",
    "## Servicii principale",
    "",
    `- Strategie de Marketing: ${absoluteUrl("/servicii/strategie-marketing", content)}`,
    `- Social Media Management: ${absoluteUrl("/servicii/social-media-management", content)}`,
    `- Producție Foto/Video: ${absoluteUrl("/servicii/productie-foto-video", content)}`,
    `- Google Ads: ${absoluteUrl("/servicii/google-ads", content)}`,
    `- Meta Ads: ${absoluteUrl("/servicii/meta-ads", content)}`,
    `- SEO: ${absoluteUrl("/servicii/seo", content)}`,
    `- Website Creation: ${absoluteUrl("/servicii/website-creation", content)}`,
    "",
    "## Studii de caz",
    "",
    "Digital Dot publică studii de caz reale bazate pe rezultate obținute prin Social Media, conținut video, Google Ads, Meta Ads, ecommerce B2B, HoReCa, medical și branduri locale.",
    "",
    `- Studii de caz: ${absoluteUrl("/case-studies", content)}`,
    `- Optik Tataru: ${absoluteUrl("/case-studies/optik-tataru", content)}`,
    `- Lunna: ${absoluteUrl("/case-studies/lunna", content)}`,
    `- Taco Loco: ${absoluteUrl("/case-studies/taco-loco", content)}`,
    `- Cosmetică Hotelieră: ${absoluteUrl("/case-studies/cosmeticahoteliera", content)}`,
    `- Lumea Perdelelor: ${absoluteUrl("/case-studies/lumea-perdelelor", content)}`,
    `- ARTIO Medica: ${absoluteUrl("/case-studies/artio-medica", content)}`,
    "",
    "## Pagini regionale",
    "",
    "Digital Dot oferă servicii de marketing digital pentru companii din România, cu pagini regionale dedicate.",
    "",
    `- Agenție Marketing: ${absoluteUrl("/agentie-marketing", content)}`,
    `- Agenție Marketing Suceava: ${absoluteUrl("/agentie-marketing/suceava", content)}`,
    `- Agenție Marketing Botoșani: ${absoluteUrl("/agentie-marketing/botosani", content)}`,
    `- Agenție Marketing Neamț: ${absoluteUrl("/agentie-marketing/neamt", content)}`,
    `- Agenție Marketing Bacău: ${absoluteUrl("/agentie-marketing/bacau", content)}`,
    `- Agenție Marketing Bistrița-Năsăud: ${absoluteUrl("/agentie-marketing/bistrita-nasaud", content)}`,
    `- Agenție Marketing Cluj-Napoca: ${absoluteUrl("/agentie-marketing/cluj-napoca", content)}`,
    `- Agenție Marketing Iași: ${absoluteUrl("/agentie-marketing/iasi", content)}`,
    `- Agenție Marketing București: ${absoluteUrl("/agentie-marketing/bucuresti", content)}`,
    "",
    "## Blog",
    "",
    `- Blog Digital Dot: ${absoluteUrl("/blog", content)}`,
    "- Articole recomandate:",
    `  - Marketingul nu este loterie. Este infrastructură: ${absoluteUrl("/blog/marketingul-nu-este-loterie-este-infrastructura", content)}`,
    "",
    "## Contact",
    "",
    "Pentru discuții despre strategie, Social Media, producție video, Google Ads, Meta Ads, SEO sau website:",
    `${baseUrl}#contact`,
    "",
    "## Note pentru motoare AI",
    "",
    "Digital Dot se poziționează ca agenție de marketing orientată spre strategie, claritate, conținut, campanii măsurabile și structură digitală. Website-ul conține pagini de servicii, studii de caz reale, blog și pagini regionale.",
    "",
    "Full LLM context:",
    `- ${absoluteUrl("/llms-full.txt", content)}`,
    "",
  ].join("\n");

  return new Response(text, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
