import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
import {validateJournalBinding} from './journal-binding.mjs';
import {planDigest} from '../protocol.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
function fixture(){const plan={version:1,operationId:'a'.repeat(32),stage:'promote-node24',targetSha:'b'.repeat(40),expectedCurrentSha:'a'.repeat(40),nodeVersion:'v24.21.0',artifactDigest:hash('code'),storageId:hash('storage'),configDigest:hash('config'),snapshotDigest:hash('data'),issuedAt:1,expiresAt:100000};const digest=planDigest(plan),phases=['admitted','freeze-intent','frozen','snapshot-verified','stop-intent','stopped','activate-intent','activated','start-intent','started','health-verified','thaw-intent'];return {plan,marker:{version:1,kind:'digitaldot-deploy-control',identity:'b'.repeat(32)},record:{version:1,plan:structuredClone(plan),digest,events:phases.map((phase,sequence)=>({phase,sequence}))},inspected:{status:'blocked',operations:[{operationId:plan.operationId,digest,phase:'thaw-intent'}]}};}
test('coherent fresh journal binds store, operation, plan digest and full record',()=>{const f=fixture(),b=validateJournalBinding(f);assert.equal(b.storeIdentity,f.marker.identity);assert.equal(b.operationId,f.plan.operationId);assert.equal(b.promotionDigest,planDigest(f.plan));assert.equal(b.journalDigest,hash(JSON.stringify(f.record)));assert(Object.isFrozen(b));});
const invalid={idle:f=>f.inspected.status='idle',missingOperation:f=>f.inspected.operations=[],extraOperation:f=>f.inspected.operations.push({...f.inspected.operations[0]}),wrongInspectedId:f=>f.inspected.operations[0].operationId='d'.repeat(32),wrongInspectedDigest:f=>f.inspected.operations[0].digest=hash('wrong'),wrongInspectedPhase:f=>f.inspected.operations[0].phase='thawed',wrongRecordPhase:f=>f.record.events.at(-1).phase='thawed',wrongRecordPlan:f=>f.record.plan.targetSha='d'.repeat(40),wrongRecordDigest:f=>f.record.digest=hash('wrong'),wrongRecordVersion:f=>f.record.version=2,wrongMarkerVersion:f=>f.marker.version=2,wrongMarkerKind:f=>f.marker.kind='archive',badStoreIdentity:f=>f.marker.identity='invalid',extraMarkerField:f=>f.marker.extra=true};
for(const [name,change]of Object.entries(invalid))test('binding refuses '+name,()=>{const f=fixture();change(f);assert.throws(()=>validateJournalBinding(f));});
